# Site settings
title: Muhammad Jaseer Khan
email: jaseerkhan123456@gmail.com
url: https://jaseerkhan.github.io
description: "Portfolio of Muhammad Jaseer Khan. Bridging technical civil engineering with strategic urban planning and transportation design to build efficient, scalable infrastructure"
keywords: "Civil Engineering, UET Peshawar, Structural Analysis, Documentaries, Public Speaking, urban planning, revit, bim, 3d bim, 4d bim, 5d bim, urban infrastructure,jaseer,jaseer khan,muhammad jaseer,muhammad jaseer khan"
skills: "Revit | AutoCad | Urban Planning"
meta_author: "Khan Muhammad Jaseer"

# Google webmaster tools
google_verify: "e6uPSH8JebHdb4n3RpRh9Mn-EgTLJy9YK8_QUX7YzjU>"

# Bing webmaster tools
bing_verify: ""

# Contact form
contact: static
disqus_shortname: ""

# Color settings
color:
  primary: '2980b9'
  primary-rgb: '41,128,185'
  secondary: '2c3e50'
  secondary-dark: '233140'

# Footer settings
footer:
  copyright: Muhammad Jaseer Khan
  location: Peshawar, Pakistan
  social: Around the Web
  credits: ""

# Social networks
social:
  - title: linkdln
    url: https://www.linkedin.com/in/mjk1175/
  - title: behance
    url: https://www.behance.net/mjk1175

# Postal address
address:
  - line: Mohallah Danda, Village Tehsil And P/O Charbagh, District Swat

# Build settings
markdown: kramdown
permalink: pretty

# For posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

# Custom Collections
collections:
  certifications:
    output: true
